"""empty message

Revision ID: 0630e5a2f3bf
Revises: 924793d6a22b
Create Date: 2017-11-25 02:20:31.979265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0630e5a2f3bf'
down_revision = '924793d6a22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('word_type', sa.String(), nullable=True),
    sa.Column('syllable_count', sa.Integer(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
