"""empty message

Revision ID: cef147d80422
Revises: 0630e5a2f3bf
Create Date: 2017-11-25 04:04:58.913565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef147d80422'
down_revision = '0630e5a2f3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('word', 'word_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('word_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('word', 'type')
    # ### end Alembic commands ###
